# Vairables start here

@rootURL = http://localhost:3000

# Vairables end here


# ------------------- USER ROUTES START HERE -------------------

// User login
POST {{rootURL}}/user/login HTTP/1.1
Content-Type: application/json

{
    "loginID": "user@test.com",
    "password": "123"
}

###



# ------------------- USER ROUTES END HERE ---------------------



# ------------------- HOTEL ROUTES START HERE ------------------

// Hotel login
POST {{rootURL}}/hotels/login HTTP/1.1
Content-Type: application/json

{
    "loginID": "hotel@test.com",
    "password": "123"
}

###


// Get all hotels
GET {{rootURL}}/super/hotels HTTP/1.1

###


// Create new Hotel
POST {{rootURL}}/super/hotels HTTP/1.1
Content-Type: application/json

{
    "hotelName": "The Siddharth International",
    "email": "hotel@test.com",
    "password": "123"
}

###


// Get hotel info
GET {{rootURL}}/hotels/1 HTTP/1.1

###


# ------------------- HOTEL ROUTES END HERE --------------------